version: '3.8'

services:
  prod-postgresql-db:
    image: postgres:16
    container_name: production-postgres-db
    restart: always
    environment:
      POSTGRES_DB: ggDB
      POSTGRES_USER: ggUser
      POSTGRES_PASSWORD: productionDBPost
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  pg_data:

